### ISSUE TITLE
автор, зачем ты меня затроллил?

### ISSUE THREAD

**Issue by werd0y45** [xTCry/VCoin#1]
я зашёл такой проверить баланс и там лежит 30к, прописываю stop И Я ПЕРЕВОЖУ ДЕНЬГИ АВТОРУ!!! АВТОР, ЗАЧЕМ ТЫ НАС ТРОЛЛИШЬ? Лучше бы автопокупку сделал ускорений

**Comment by xTCry** [comment]
Скоро поправлю этот назойливый донат

**Comment by werd0y45** [comment]
я теперь прожимаю 0 перед командами, чтобы ты не затроллил снова!!!!

**Comment by x8fqn** [comment]
Замени циферки на свой ID в файле VCoinWS.js в строчке 397, тогда коины будут перечислятся тебе при любом токене.
(Но если есть возможность, отблагодари автора скриптa коинами, он старался :) )
![изображение](https://user-images.githubusercontent.com/25567679/55483874-28890c80-5630-11e9-9f5f-dd4a542efc46.png)
 upd. Можешь отключить это закомментировав index.js:38
![изображение](https://user-images.githubusercontent.com/25567679/55484566-6470a180-5631-11e9-9e31-f180a87de100.png)
P.S. @xTCry, можно приостановить работу скрипта при просьбе о донате, а то консоль засоряется и сообщение теряется ;3

**Comment by xTCry** [comment]
> P.S. @xTCry, можно приостановить работу скрипта при просьбе о донате, а то консоль засоряется и сообщение теряется ;3

Готово
