### ISSUE TITLE
Unexpected server response: 502

### ISSUE THREAD

**Issue by agalq12** [xTCry/VCoin#11]
[04.04.2019 03:04:17]: Try start...
Unexpected server response: 502
[04.04.2019 03:04:17]: onOffline
Попытка рестарта через 20 секунд
что делать

**Comment by xTCry** [comment]
> что делать

Остается только ждать
![image](https://user-images.githubusercontent.com/5994290/55521633-38353f00-568a-11e9-80e7-ae15df8674f6.png)
![image](https://user-images.githubusercontent.com/5994290/55521658-4b480f00-568a-11e9-893d-695d31868d6c.png)

**Comment by Edmorea** [comment]
Такая же проблема. Сутки работала норм, а сейчас вообще ни в какую 
![image](https://user-images.githubusercontent.com/40120252/55565887-5a1ed800-5703-11e9-9814-ff7fe976345c.png)

**Comment by imslava** [comment]
Чет сломался

![image](https://user-images.githubusercontent.com/47377277/55566127-43897880-5725-11e9-8d5e-e8539c582887.png)

**Comment by vladdd183** [comment]
Вк щас сервера переносят, у многих может не работать и лагать, попробуйте первым на перво, установить последнюю версию скрипта и заменить токен
