### ISSUE TITLE
Майнинг от имени сообщества

### ISSUE THREAD

**Issue by 01HeLLBoY92** [xTCry/VCoin#12]
Достаточно ли после токена дописать -u https://vk.com/app6915965_-ид_сообщества ?

**Comment by raywave** [comment]
нет

**Comment by raywave** [comment]
ссылка получается совершенно другим образом.

**Comment by 01HeLLBoY92** [comment]
@cursedseal Емли не трудно, то скажи как)

**Comment by raywave** [comment]
гайды есть, трудно. сегодня обновлю ридми в vcoinx с подробным гайдом, как получить правильный токен, как получить ссылку.

**Comment by 01HeLLBoY92** [comment]
@cursedseal оке, буду ждать

**Comment by kyoukisu** [comment]
> гайды есть, трудно. сегодня обновлю ридми в vcoinx с подробным гайдом, как получить правильный токен, как получить ссылку.

можно ссылку на гайд?

**Comment by maksam07** [comment]
Думаю можно закрывать)

**Comment by 01HeLLBoY92** [comment]
Так как разраб жлоб и не дает линк на гайд, я закрываю

**Comment by maksam07** [comment]
> Так как разраб жлоб и не дает линк на гайд, я закрываю

в новой версии либы можно указать параметром группу, в которую лить коины
> -gid 123
