### ISSUE TITLE
prices

### ISSUE THREAD

**Issue by Probeo1312** [xTCry/VCoin#13]
после обновы не показывает цену на datacenter & quantum pc

**Comment by cursedseal** [comment]
воспроизводится, нужно добавить true в lprices.

в vcoinx пофикшено.

**Comment by raywave** [comment]
приложи скриншоты.

**Comment by vladdd183** [comment]
![изображение](https://user-images.githubusercontent.com/26278260/55567218-e500d200-5705-11e9-8f1b-e193d7300879.png)

Я мельком глянул код, там походу всё по ID делается, денег у меня недостаточно, чтобы купить что-то другое и проверить, но похоже на то, что у них ID сменились, если прошлых код с ценами не трогался

**Comment by vladdd183** [comment]
Странно работает, не могу отловить баг, похоже что это зависит от денег, каким-то образом
![изображение](https://user-images.githubusercontent.com/26278260/55567570-9e5fa780-5706-11e9-8b9b-558f5d130020.png)

**Comment by vladdd183** [comment]
![изображение](https://user-images.githubusercontent.com/26278260/55567622-b800ef00-5706-11e9-9373-5405949d79ed.png)
Да, зависит от денег

**Comment by vladdd183** [comment]
Нашёл строку в которой баг, к сожалению в синтаксисе JS не разбираюсь, может кто и сделает пул-реквест
https://github.com/xTCry/VCoin/blob/486b332e986beb917f4d8175675d49287fb128f7/index.js#L157

**Comment by xTCry** [comment]
В обнове фикс скоро
