### ISSUE TITLE
Как понять работает ли автопокупка? Я ее включил и выбрал что покупать , а она не покупает ничего.

### ISSUE THREAD

**Issue by LeqiXx** [xTCry/VCoin#16]

**Comment by vladdd183** [comment]
Нужно ввести так 
node index.js -t *TOKEN* -autobuy -autobuyItem *Предмет, который покупать*

**Comment by vladdd183** [comment]
При достаточном колличестве денег, он будет покупать этот предмет

**Comment by xtvfrc123** [comment]
> Нужно ввести так
> node index.js -t _TOKEN_ -autobuy -autobuyItem _Предмет, который покупать_

я ввёл так и ничего, по прежнему не покупает

**Comment by vladdd183** [comment]
Он покупает, но не выводит сообщение об этом, последите за счётом, при достаточном уровне денег, они тратятся

**Comment by xtvfrc123** [comment]
> Он покупает, но не выводит сообщение об этом, последите за счётом, при достаточном уровне денег, они тратятся

не вижу изменений счёта на 40к

**Comment by xtvfrc123** [comment]
> Он покупает, но не выводит сообщение об этом, последите за счётом, при достаточном уровне денег, они тратятся

коинов в избытке, и как прописать допустим не 1 итем а что бы ещё сервер например покупало, через пробел просто после датацентра?

**Comment by vladdd183** [comment]
При запуске скрипта показало, что выбрано для автопокупки?

**Comment by xtvfrc123** [comment]
да


> При запуске скрипта показало, что выбрано для автопокупки?

**Comment by vladdd183** [comment]
> > Он покупает, но не выводит сообщение об этом, последите за счётом, при достаточном уровне денег, они тратятся
> 
> коинов в избытке, и как прописать допустим не 1 итем а что бы ещё сервер например покупало, через пробел просто после датацентра?

Можно выбрать только 1 вещь для покупки, вроде как

**Comment by xtvfrc123** [comment]
![image](https://user-images.githubusercontent.com/49272337/55553375-314e1100-570a-11e9-9894-e16eb09efb24.png)

**Comment by xtvfrc123** [comment]
> > > Он покупает, но не выводит сообщение об этом, последите за счётом, при достаточном уровне денег, они тратятся
> > 
> > 
> > коинов в избытке, и как прописать допустим не 1 итем а что бы ещё сервер например покупало, через пробел просто после датацентра?
> 
> Можно выбрать только 1 вещь для покупки, вроде как

ну даже эту одну вещь он не покупает

**Comment by vladdd183** [comment]
![изображение](https://user-images.githubusercontent.com/26278260/55553439-d7891f00-56e8-11e9-9db4-88fd2415f144.png)
Вот часть кода, отвечающая за автопокупку

**Comment by vladdd183** [comment]
Кстати, при команде "price" не выводит цены на датацентры

**Comment by xtvfrc123** [comment]
> ![изображение](https://user-images.githubusercontent.com/26278260/55553439-d7891f00-56e8-11e9-9db4-88fd2415f144.png)
> Вот часть кода, отвечающая за автопокупку

мне это ничего не говорит)

**Comment by vladdd183** [comment]
Возможно, датацентры пока ещё не доступны для покупки, попробуйте, для эксперимента что-то другое

**Comment by xtvfrc123** [comment]
хорошо, сейчас проверю

**Comment by xtvfrc123** [comment]
![image](https://user-images.githubusercontent.com/49272337/55553669-0617f180-570b-11e9-9e7a-1e17dc9240fd.png)
![image](https://user-images.githubusercontent.com/49272337/55553675-0a440f00-570b-11e9-99cb-1e67db92a398.png)

**Comment by vladdd183** [comment]
Действительно, при запуске автопокупка похоже не работает, но можно во время запущенного скрипта включать.
Когда скрипт запущен введите "autoBuyItem"
И потом вам предложат что купить

**Comment by xtvfrc123** [comment]
![image](https://user-images.githubusercontent.com/49272337/55554079-18def600-570c-11e9-925b-fc4fcf0ef016.png)
ну что то всё равно е покупает

**Comment by xtvfrc123** [comment]
с курсором также не работает

**Comment by vladdd183** [comment]
Странная вещь, у меня сразу с ума сошел, начал все курсоры скупать, у вас тожно последняя версия?

**Comment by xtvfrc123** [comment]
VCoinX у меня

**Comment by raywave** [comment]
@xtvfrc123 [VCoinX issues](https://github.com/cursedseal/VCoinX/issues)

**Comment by vladdd183** [comment]
Топик можно закрывать, если что
