### ISSUE TITLE
не ворк

### ISSUE THREAD

**Issue by fqhy** [xTCry/VCoin#19]
![image](https://user-images.githubusercontent.com/49283302/55568535-8ab54080-5708-11e9-9083-6a6c7329fb5a.png)

**Comment by vladdd183** [comment]
Создайте файл ".config.js"

**Comment by fqhy** [comment]
он создан,  лул

**Comment by fqhy** [comment]
![image](https://user-images.githubusercontent.com/49283302/55568761-f9929980-5708-11e9-845a-c4608fa390db.png)

**Comment by vladdd183** [comment]
Все зависимости установили?

**Comment by fqhy** [comment]
да, все

**Comment by vladdd183** [comment]
Похоже на то, что что-то не установилось, та ли версия node'а?

**Comment by fqhy** [comment]
стоит, 100% выше 8.

**Comment by kageminori** [comment]
Работало +- сутки. Теперь все время это вылезает
![image](https://user-images.githubusercontent.com/40120252/55569972-2d6ebe80-570b-11e9-88eb-80e220c60989.png)

**Comment by vladdd183** [comment]
> Работало +- сутки. Теперь все время это вылезает
> ![image](https://user-images.githubusercontent.com/40120252/55569972-2d6ebe80-570b-11e9-88eb-80e220c60989.png)

Щас сервера переносят, может у многих не работать, попробуйте сгенерировать новый токен, если не получится, попробуйте новую версию установить и тоже новый токен, если так же, то проблема не у вас

**Comment by kageminori** [comment]
Не работает (9( Обнову ждать? ОНа будет?
> > Работало +- сутки. Теперь все время это вылезает
> > ![image](https://user-images.githubusercontent.com/40120252/55569972-2d6ebe80-570b-11e9-88eb-80e220c60989.png)
> 
> Щас сервера переносят, может у многих не работать, попробуйте сгенерировать новый токен, если не получится, попробуйте новую версию установить и тоже новый токен, если так же, то проблема не у вас

**Comment by Ivan-Khar** [comment]
> стоит, 100% выше 8.

Крч удаляете папку node_modules и опять запускаете npm install
У меня помогло.

Больше интересует баг с onBrokenEvent
Как исправить то? :D

**Comment by xTCry** [comment]
Ждать обнову
