### ISSUE TITLE
Автор ты троль????

### ISSUE THREAD

**Issue by kroilik** [xTCry/VCoin#2]
скачал твою праграму установил завистимости npm i, и кароче пишу хелп появляется прикол
`Error: Cannot find module './.config.js'`
праверял на windows и ещё установил на роутер))) там такая же проблема...,

**Comment by kroilik** [comment]
Фиксится если заранее создать пустой файл config.js, а так же  в index.js 7 строку
`let { USER_ID, DONEURL, VK_TOKEN } = require('./.config.js');`
изменить, убрав лишнюю точку
`let { USER_ID, DONEURL, VK_TOKEN } = require('./config.js');`

**Comment by xTCry** [comment]
Запуск приложения подразумевается из директории с index файлом, поэтому и есть `./`

> Фиксится если заранее создать пустой файл config.js, а так же в index.js 7 строку

В документации написано, что нужно создать файл

**Comment by kroilik** [comment]
Да по поводу файла ясно всё) 
В  файле указано именно `./.`, таким образом он никак не стартует

**Comment by a1keen** [comment]
> Да по поводу файла ясно всё)
> В файле указано именно `./.`, таким образом он никак не стартует

Так в документации было написано создать именно .config.js
