### ISSUE TITLE
Фарм коинов для сообщества

### ISSUE THREAD

**Issue by Kiri483** [xTCry/VCoin#22]
Как фармить токены через сообщество? Можете дать гайд пожалуйста.
![image](https://user-images.githubusercontent.com/43967304/55575610-b0524200-5728-11e9-9adf-5895e33abcbe.png)

**Comment by raywave** [comment]
гайда не будет, наверное. в ссылке сам можешь изменить.

мб разраб позднее добавить эту фишку

**Comment by Kiri483** [comment]
> гайда не будет, наверное. в ссылке сам можешь изменить.
> 
> мб разраб позднее добавить эту фишку

можешь сказать как это сделать?

**Comment by 01HeLLBoY92** [comment]
Так ты скажи что изменить надо)

**Comment by Kiri483** [comment]
> Так ты скажи что изменить надо)

Хочу фарм токенов для сообщества сделать
