### ISSUE TITLE
WTF onBrokenEvent Ошибка?

### ISSUE THREAD

**Issue by LifeViwer** [xTCry/VCoin#23]
Ошибка из-за чего такое может, весь отлично всё работало
![image](https://user-images.githubusercontent.com/36803375/55576154-0e335980-572a-11e9-9b31-1ca8ce0ceb52.png)
.

**Comment by dygoo** [comment]
видимо вк шалит, same shit

**Comment by Glebsin** [comment]
То же самое на разных акках, иногда помогает с телефона перезайти или что то купить

**Comment by LifeViwer** [comment]
Капец все аккаунты уже почти так, что за фигня IP менял не помогает(

**Comment by k4ffy** [comment]
Нашёл фикс: 1. закрываете консоль
2. заходите через акк в игру
3. снова запускаете бота

**Comment by dygoo** [comment]
Рандомная фигня, перезапускайте, пока не заработает)

**Comment by waslosted** [comment]
а что если ` ...*: USER_ID%**16***/`

**Comment by kageminori** [comment]
Все еще 
![image](https://user-images.githubusercontent.com/40120252/55580252-d379f300-5722-11e9-96a0-7164a3995c77.png)

**Comment by D34n0n** [comment]
Пробуйте вводить stop и run до посинения пальцев. Лично мне помогло /shrug
![Снимок](https://user-images.githubusercontent.com/49290313/55585064-76843a00-572e-11e9-81db-163af3e3ec64.PNG)

**Comment by LifeViwer** [comment]
> Пробуйте вводить stop и run до посинения пальцев. Лично мне помогло /shrug
> ![Снимок](https://user-images.githubusercontent.com/49290313/55585064-76843a00-572e-11e9-81db-163af3e3ec64.PNG)

Блин реально же 2 аккаунта реанимировал)

**Comment by xTCry** [comment]
Fixed
