### ISSUE TITLE
onBrokenEvent Ошибка (Знаю что у многих так)

### ISSUE THREAD

**Issue by Ivan-Khar** [xTCry/VCoin#26]
![image](https://user-images.githubusercontent.com/47220198/55582203-8f3d2180-5727-11e9-8e3c-4d6a49854140.png)

Такая же проблема как и у многих. Пробовал stop и run. У меня Автоматически кликает 31 в секунду. Есть ли решение данной проблемы?

**Comment by Ivan-Khar** [comment]
Не знаю как. Но оно начало работать. но на долго ли - я не знаю. Получилось при включении кликера -> запуск вк коин на телефоне и при ожидании 20 секунд оно заработало.

**Comment by LifeViwer** [comment]
Пожалуйста давайте все вместе фиксанём этот БАГ, где прогеры, я уже кучу всего перепробывал ни как не могу понять из -за чего эта ошибка(

**Comment by xzeldon** [comment]
Вообщем, нашел временный фикс. Первое, что вы должны сделать, если у вас версия, скачанная с гитхаба, то это остановить бота. Теперь зайдите в файл index.js, в строке номер 447 замените то, что там на `URLWS = URLWS.replace("coin.vkforms.ru", (CHANNEL>7)? "bagosi-go-go.vkforms.ru": "coin.w5.vkforms.ru");`   После этого убедитесь, что вы используете авторизацию через токен. Теперь делаем себе новый токен, в README.md рассказано, как сделать. Заходим в файл .config.js (если его нет, создайте, вставьте туда этот код:`module.exports = {
  VK_TOKEN: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
};`. Буквы "А" заменяем нашим токеном. Готово. Запускаем скрипт, все должно работать. Проверено 5 людьми на более чем 10 аккаунтах. Решение временное, так как токен приходится менять после каждого перезапуска.

**Comment by Ivan-Khar** [comment]
Ну насмешил, то что второе - должно робить, но то что ты написал первое - накопление коинов на группу багосы)0)0 Ну мне не жалко, пусть

**Comment by xzeldon** [comment]
> Вообщем, нашел временный фикс. Первое, что вы должны сделать, если у вас версия, скачанная с гитхаба, то это остановить бота. Теперь зайдите в файл index.js, в строке номер 447 замените то, что там на `URLWS = URLWS.replace("coin.vkforms.ru", (CHANNEL>7)? "bagosi-go-go.vkforms.ru": "coin.w5.vkforms.ru");` После этого убедитесь, что вы используете авторизацию через токен. Теперь делаем себе новый токен, в README.md рассказано, как сделать. Заходим в файл .config.js (если его нет, создайте, вставьте туда этот код:`module.exports = { VK_TOKEN: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA", };`. Буквы "А" заменяем нашим токеном. Готово. Запускаем скрипт, все должно работать. Проверено 5 людьми на более чем 10 аккаунтах. Решение временное, так как токен приходится менять после каждого перезапуска.

Заметил, что когда через оф.клиент вк приходят уведомления о сообщениях и т.д., появляется та самая ошибка onBrokenEvent. В моем случае решение просто: я закрыл вк, обновил опять токен и все заработало.

**Comment by DanielSpravtsev** [comment]
[Облачко.](https://socks4.ru/)

**Comment by xTCry** [comment]
Исправлено
