### ISSUE TITLE
Автоматический выбор выгодных ускорений

### ISSUE THREAD

**Issue by L3Nya** [xTCry/VCoin#28]
Бот сам должен выбирать более выгодные ускорения.
Например квантовый компьютер в 3 раза дешевле чем дата-центр, а 2 квантовых ПК == 1 дата-центру. => надо взять квантовый ПК.

**Comment by x8fqn** [comment]
Или выбирать вариант, там где выгоднее цена за коин/мин

**Comment by maksam07** [comment]
Вы можете сами дописать рассчет, у меня это занято примерно 25 строк кода
![image](https://user-images.githubusercontent.com/24889043/55614508-c5b18580-5795-11e9-9d4e-af9ea73cd1aa.png)

**Comment by r1veo** [comment]
> Вы можете сами дописать рассчет, у меня это занято примерно 25 строк кода
> ![image](https://user-images.githubusercontent.com/24889043/55614508-c5b18580-5795-11e9-9d4e-af9ea73cd1aa.png)

Не мог бы ты дать код?

**Comment by themagic314** [comment]
Я думаю можно закрывать. #32
