### ISSUE TITLE
энчантикс

### ISSUE THREAD

**Issue by raywave** [xTCry/VCoin#30]
так в общем, пришла идея.
во время создания интерфейса ввода, можно сделать параметр, который на время ввода будет замораживать все выходящие сообщения (хук в helpers), а после окончания интерфейса их выводить.

**Comment by xTCry** [comment]
Разве сейчас не замораживается в режиме ввода? 🤔 
Разве что обратно не выводит

**Comment by Romz24** [comment]
@xTCry, на linux не замораживается, флудит.

![Povyht9Z15Y](https://user-images.githubusercontent.com/2458113/55636953-ae41bf00-57cc-11e9-8990-adf0c287b672.jpg)

**Comment by x8fqn** [comment]
@Romz24, ты ввёл "help", зачем что-то замораживать?

**Comment by Romz24** [comment]
@Heyyouman, не приятно вводить команды когда в консоли флудит.

**Comment by x8fqn** [comment]
@Romz24, согласен. Думаю, стоит выделить последнюю строчку под ввод команд.
