### ISSUE TITLE
идея по улучшению (нет)

### ISSUE THREAD

**Issue by raywave** [xTCry/VCoin#4]
короче можешь сделать так, что при генерации ссылки через токен оно генерировалось на твою группу. статистика тебе - убытка людям нет.

**Comment by xTCry** [comment]
Это тоже попробую реализовать, но чуть позже


Если нужно на группу, то можно указать свою ссылку. Но и самому ее где-то получить

**Comment by raywave** [comment]
Довольно стебная идея, айди группы находится в ссылке на приложение (vk_group_id).

**Comment by AriyKrestovozdvijhenski** [comment]
Приложение хорошее, никаких улучшений не требует, но в последнем обновлении приложение после открытия майнинга через телефон не возобновляется автоматически, а пишет ошибку и всё

**Comment by tralal** [comment]
чтобы можно было майнить в одной консоле неограниченное колво акков

**Comment by GoldFreddy** [comment]
чтобы при майнинге всё время выводилась текущая скорость

**Comment by markwell26** [comment]
Вышло обновление бота, добавили умную автопокупку, сегодня в неоригинальном это будет?
