### ISSUE TITLE
Удоли

### ISSUE THREAD

**Issue by feed4rz** [xTCry/VCoin#41]
![image](https://user-images.githubusercontent.com/13008534/55650971-df7fb680-57ef-11e9-954c-4e322aace811.png)

Слишком палишься бро

**Comment by Romz24** [comment]
Читать не учили?

![ScreenShot00063](https://user-images.githubusercontent.com/2458113/55651486-713bf380-57f1-11e9-9853-b0185b408716.jpg)

**Comment by SonicProgramming** [comment]
Братан, это FOSS, ты в курсе что ты можешь это поменять, окда?

**Comment by feed4rz** [comment]
@Romz24 сорян, вопрос закрыт, без базара
