### ISSUE TITLE
Молю, сделай команду на вывод скорости.

### ISSUE THREAD

**Issue by starcevpro** [xTCry/VCoin#45]
Сделай команду на получение скорости. Это будет очень удобно. На данный момент скорость показываеться если только что-то купить или при запуске.

**Comment by kyoukisu** [comment]
поддерживаю

**Comment by Wasswolle** [comment]
поддерживаю+

**Comment by kyoukisu** [comment]
Решение на коленке
Файл VCoinWS.js
В функцию на 313 строчке (примерно) под названием onTickEvent вставляем данную строку
`console.log("! Доход " + this.tick/1000);`

**Comment by kyoukisu** [comment]
[VCoinWS.txt](https://github.com/xTCry/VCoin/files/3050164/VCoinWS.txt)
(для ленивых на ваш страх и риск, если там скрытый майнер - я не виноват)
качаете, меняете формат на .js 
заменяете в папке

**Comment by starcevpro** [comment]
Это конечно не команда, но я сделал лучше, теперь выводит в лог.
По идее можно и команду добавить... ( vConinWS.tick )
Замените строку **153** в **index.js**:
`con("В ТОПе: " + place + "\tСЧЕТ: "+ formateSCORE(score, true), "yellow");`
на
`con("В ТОПе: " + place + "\tСЧЕТ: "+ formateSCORE(score, true) + "\tСКОРОСТЬ: " + formateSCORE(vConinWS.tick, true), "yellow");`
