### ISSUE TITLE
ReferenceError: Window is not Defined

### ISSUE THREAD

**Issue by UsermanLC** [xTCry/VCoin#49]
Даже не знаю что ещё добавить. В старой версии сижу, было все хорошо, тут вот, ошибка из тайтла. Что делать?

**Comment by thedeaddan** [comment]
Зайди в консоль из папки (SHIFT+ПКМ в пустом месте) и обнови зависимости (npm i) 
![image](https://user-images.githubusercontent.com/40400854/55664882-6fe4e800-583e-11e9-813c-bf93dd1a0af7.png)

**Comment by g00se** [comment]
Чтобы исправить window is not Defined  нужно добавить 

`pow = "var window = {};window['location'] = { host: \"https://vk.com\"};" + pow;`
в файл **VCoinWS.js** перед строчкой 
if(pow)
 try {
                                let x = eval(pow),

**Comment by thedeaddan** [comment]
А вот то что я сказал вообще никого не ибет?(

**Comment by D34n0n** [comment]
Лол, но у меня заработало без всех выше предложенных инструкций)))
Скорее всего, это одна из ошибок onBrokenEvent (но это не точно)
![image](https://user-images.githubusercontent.com/49290313/55666887-89e1f300-585d-11e9-80ec-f24d27ea7bc4.png)

**Comment by thedeaddan** [comment]
Мне помогал перезапуск, полная переустановка кроме конфига(соединяй предпоследнюю версию и последнюю, тк в последней не хватает файлов (возможно так и надо, но у меня так работает и заебок) обновляй зависимости) и четко

**Comment by xTCry** [comment]
уже фикс
