### ISSUE TITLE
-smartbuy не работает как параметр при запуске

### ISSUE THREAD

**Issue by mlv-dev** [xTCry/VCoin#52]
При запросе cmd типа `node  index.js <...> -smartbuy` smartbuy игнорируется.
Включается только при уже работающем скрипте командой smartbuy

**Comment by hkJgu8rG0qaWcvaPu3vhlycaKc2Tfb8u** [comment]
Действительно

**Comment by madf12** [comment]
Потому что нужно использовать ключ `-smartBuy`

**Comment by mlv-dev** [comment]
Пофиксил
