### ISSUE TITLE
Datacenter не отображается по команде buy

### ISSUE THREAD

**Issue by mlv-dev** [xTCry/VCoin#59]
![image](https://user-images.githubusercontent.com/35173722/55673369-fbe32800-58af-11e9-9f2a-bf2fd28ae255.png)

**Comment by k0tletka** [comment]
Он не будет отображаться если у тебя на него недостаточно денег

**Comment by k0tletka** [comment]
Написано же: "Доступные" ускорения)

**Comment by mlv-dev** [comment]
Надо бы добавить "На какие хватает клинов". Так неочевидно
