### ISSUE TITLE
перевод

### ISSUE THREAD

**Issue by 4ypik** [xTCry/VCoin#6]
каким образом осуществляется перевод коинов? По айди? Токену? Как?

**Comment by Mepth** [comment]
Команда "tran", по id пользователя

**Comment by xTCry** [comment]
Пока что при переводе будет ошибка
![image](https://user-images.githubusercontent.com/5994290/55505819-a19e5900-565c-11e9-94cf-a34aa56792b7.png)
то же самое и с покупкой
