### ISSUE TITLE
Перестал работать майнер

### ISSUE THREAD

**Issue by TheKoT** [xTCry/VCoin#63]
![Безымя](https://user-images.githubusercontent.com/49349247/55673936-e4b03480-58c7-11e9-8a74-656e3d4a95d4.png)

**Comment by qweanhri** [comment]
та же фигня)

**Comment by thedeaddan** [comment]
Это сервер вк

**Comment by anspirer** [comment]
+1

**Comment by TheKoT** [comment]
UPD: Проблема решена, разработчик залил фикс
Не включайте звук(команда beep), а то -уши xD
