### ISSUE TITLE
Ошибка получения токена

### ISSUE THREAD

**Issue by dancebunny98** [xTCry/VCoin#64]
![image](https://user-images.githubusercontent.com/37336183/55674101-ad865700-58b8-11e9-9dc4-5a873976c59b.png)

Токен в конфиге прописан!

**Comment by thedeaddan** [comment]
Чёт на твоей стороне, ни у кого не было такой ошибки, скачай последнюю версию и создай новый конфиг, так же желательно npm i сделать)
