### ISSUE TITLE
Не работает время автоперевода

### ISSUE THREAD

**Issue by 01HeLLBoY92** [xTCry/VCoin#71]
Не работает таймер для автоперевода. Пиши хоть сколько секунд, но все равно будет 3600

**Comment by Romz24** [comment]
у меня работает, покажите как параметры прописаны

**Comment by telikey** [comment]
У меня тоже не рубит 
Попробуй поменять параметр в коде в файле index.js
`transferScore = 3e5, - сколько переводить
 transferInterval = 36e2, -интервал перевода`
У меня сработало

**Comment by xTCry** [comment]
Проверю, налажу

**Comment by 01HeLLBoY92** [comment]
> у меня работает, покажите как параметры прописаны

![image](https://user-images.githubusercontent.com/38907734/55708752-0b867c00-5a2a-11e9-925f-8c2ba9f8e8bc.png)
