### ISSUE TITLE
Разовый перевод

### ISSUE THREAD

**Issue by mrGooDMaster** [xTCry/VCoin#76]
Предложение, добавить разовый перевод.

**Comment by D34n0n** [comment]
В каком смысле? Перевод каких угодно сумм кому угодно уже доступен

**Comment by mrGooDMaster** [comment]
-to -tsum без указания -ti [seconds] будет разовым переводом или он будет повторятся раз в 3600с?

**Comment by Romz24** [comment]
Используйте команду **tran**, вот как это работает:

![Kbu83zOmScY](https://user-images.githubusercontent.com/2458113/55741807-d3396a80-5a36-11e9-9a38-618d9ed9247d.jpg)
