### ISSUE TITLE
Глюк smartbuy

### ISSUE THREAD

**Issue by mozgoverflow** [xTCry/VCoin#79]
Пример на скриншоте.

Процесс выглядит так, будто копятся деньги на одно улучшение, но покупается другой. В данном случае копились на датацентр, но в итоге была куплена стойка видеокарт. 

Баг происходит уже второй раз, в первый раз помогла перезагрузка бота.

![image](https://user-images.githubusercontent.com/19547251/55744136-7b016900-5a34-11e9-8079-2d246b112e6d.png)

**Comment by hkJgu8rG0qaWcvaPu3vhlycaKc2Tfb8u** [comment]
Да, заметил недавно тоже.

**Comment by themagic314** [comment]
Все дело вот в этой функции **justPrices()** из которой получается цена покупки. В случае если денег не хватает, то она возвращает 0. Соответсвенно smartbuy в switch всегда уходит в предмет на который не хватает денег и **miner.hasMoney(smartBuyItem){}** даже не выполняется. А "умная покупка" происходит только в случае если денег хватает на все предметы.

При том, что у @ravensoracle в ПР все было правильно, но потом вот этот комит все сломал.
[CommitLink](https://github.com/xTCry/VCoin/commit/09feac7a2f357d2a6a14e4010bccc9c29588997f#diff-168726dbe96b3ce427e7fedce31bb0bcL230)

**Comment by xTCry** [comment]
> При том, что у @ravensoracle в ПР все было правильно, но потом вот этот комит все сломал.
> [CommitLink](https://github.com/xTCry/VCoin/commit/09feac7a2f357d2a6a14e4010bccc9c29588997f#diff-168726dbe96b3ce427e7fedce31bb0bcL230)

Поправил в следующих коммитах. Проверьте

**Comment by impaxel** [comment]
> Поправил в следующих коммитах. Проверьте

Проблема всё ещё актуальна на 1.4.7

**Comment by xTCry** [comment]
Исправил и снова сломал

Хотя уже не актуально
