### ISSUE TITLE
Авто-продолжение майнинга

### ISSUE THREAD

**Issue by MarkelovZ** [xTCry/VCoin#8]
Бывает такое... Оставляешь бота на долгое время... Приходишь, а он через 40 мин работы умер с ошибкой и вообще вылетел скрипт  (опять надо писать node index.js...

Исправьте умоляю)  На ночь даже не оставишь

**Comment by xTCry** [comment]
Сейчас пока что все лежит
![image](https://user-images.githubusercontent.com/5994290/55511245-c5679c00-5668-11e9-85cf-b14bfb565083.png)

**Comment by x8fqn** [comment]
Перестало работать
![изображение](https://user-images.githubusercontent.com/25567679/55512488-f6959b80-566b-11e9-9c5d-03232f866859.png)

**Comment by xTCry** [comment]
Там у них сервер переезжал 
Теперь все снова в строю (почти)

**Comment by kageminori** [comment]
Все работает шикарно, четкий скрипт(?)

**Comment by beehunt9r** [comment]
Nodemon поставь и не парься.
