### ISSUE TITLE
У кого недействительный токен - сюды

### ISSUE THREAD

**Issue by maksam07** [xTCry/VCoin#83]
Не получается установить ID группы, ошибка:

[ОШИБКА]: Code №3 - Unknown method passed: function not found, please check https://vk.com/editapp?id=6334949&section=functions
[ОШИБКА]: Токен стал недействительным.
API Error: The end.

Если самому собрать линку:
https://api.vk.com/method/execute.resolveScreenName?access_token=...&v=5.55&screen_name=app6915965_...&owner_id=...&func_v=3

Результат будет примерно такой:
error_code: 3
error_msg: "Unknown method passed: function not found, please check https://vk.com/editapp?id=6334949&section=functions"

Если вырезать функционал получения ссылки для группы, то все работает

> P.S. Разобрался. Токена от клевера уже недостаточно, нужно получать нормальный
> https://oauth.vk.com/token?grant_type=password&client_id=2274003&client_secret=hHbZxrka2uZ6jB1inYsH&username=YLOGIN&password=YPASSWORD&v=5.92
> У кого 2fa:
> https://oauth.vk.com/token?grant_type=password&client_id=2274003&client_secret=hHbZxrka2uZ6jB1inYsH&username=YLOGIN&password=YPASSWORD&v=5.92&2fa_supported=1&code=111
> YLOGIN - ваш логин
> YPASSWORD - ваш пароль
> code - любой из резервных кодов

**Comment by DiFFoZ** [comment]
"error":"need_captcha" не работает

**Comment by KyKyIIIKuH** [comment]
у меня вообще чудеса
ввожу правильные данные 
итог:

> {"error":"invalid_client","error_type":"username_or_password_is_incorrect","error_description":"Неправильный логин или пароль"}

**Comment by maksam07** [comment]
> "error":"need_captcha" не работает

Пример ответа при необходимости ввода CAPTCHA:
{"error":"need_captcha","captcha_sid":"854844498568","captcha_img":"http:\/\/api.vk.com\/captcha.php?sid=854844498568&s=1"}

В этом случае необходимо повторить запрос, добавив к нему следующие параметры:
captcha_sid — поле captcha_sid, полученное в предыдущем запросе;
captcha_key — то, что ввёл пользователь.

**Comment by maksam07** [comment]
> у меня вообще чудеса
> ввожу правильные данные
> итог:
> 
> > {"error":"invalid_client","error_type":"username_or_password_is_incorrect","error_description":"Неправильный логин или пароль"}

Только что чекнул, все работает. Вводи правильные данные. Линки подправил

**Comment by KyKyIIIKuH** [comment]
> > у меня вообще чудеса
> > ввожу правильные данные
> > итог:
> > > {"error":"invalid_client","error_type":"username_or_password_is_incorrect","error_description":"Неправильный логин или пароль"}
> 
> Только что чекнул, все работает. Вводи правильные данные. Линки подправил

может это из-за того что я email использую для логина?
или пофиг должно быть?

**Comment by maksam07** [comment]
> или пофиг должно быть?

Именно. У меня акки и с номерами, и с мылом - все авторизовывается. Попробуй в этом же браузере войти в акк под данными, которые прописываешь в линке. Линка - прямая авторизация

**Comment by KyKyIIIKuH** [comment]
> > или пофиг должно быть?
> 
> Именно. У меня акки и с номерами, и с мылом - все авторизовывается. Попробуй в этом же браузере войти в акк под данными, которые прописываешь в линке. Линка - прямая авторизация

проблема была в пароле, символы ему не нравились

**Comment by DiFFoZ** [comment]
![image](https://user-images.githubusercontent.com/48765566/55854292-7650c800-5b8e-11e9-95b9-763ee9e09b53.png)
Спасибо

**Comment by xTCry** [comment]
Теперь подходит почти любой токен
