### ISSUE TITLE
После обновы ошибонька

### ISSUE THREAD

**Issue by Cobr3n** [xTCry/VCoin#84]
![image](https://user-images.githubusercontent.com/25749976/55852745-5d451880-5b88-11e9-9bd6-fdbc0625366c.png)
PS: токен новый сгенерил всеравно не катит

**Comment by Cobr3n** [comment]
С телефона тоже не заходит, с веб версии все по нулям )

**Comment by maksam07** [comment]
Чел, ну хоть бы почитал другие проблемы. Я ж вот только писал о ней

**Comment by Cobr3n** [comment]
Спасибо закрываем)
