### ISSUE TITLE
Как запустить на новой версии с конфигом DONEURL:

### ISSUE THREAD

**Issue by sh1man** [xTCry/VCoin#86]
Как запустить на новой версии с конфигом DONEURL: "https://coin-without-bugs.vkforms.ru/..."
при попытки запуска лаунчера всегда требует токен и пароль.

**Comment by xTCry** [comment]
Сейчас поправлю

**Comment by sh1man** [comment]
> Сейчас поправлю

В данный момент ошибка теперь code 5 invalid token (4)
