### ISSUE TITLE
У кого ошибка e.replace при переводе коинов или чего-то еще [решение]

### ISSUE THREAD

**Issue by maksam07** [xTCry/VCoin#87]
Заменяем функцию onlyInt в helpers.js на
```
function onlyInt(e) {
	return parseInt(e.toString().replace(/\D+/g,""));
}
```
а так же в index.js заменить все вхождения formatScore (их 2) на format**e**Score (разраб не везде изменил название функции)

**Comment by xTCry** [comment]
Done
