### ISSUE TITLE
Не запускается майн после обновления 10.04.2019

### ISSUE THREAD

**Issue by pandaDS3** [xTCry/VCoin#88]
Обновил майнер, не запускалось, токены были недействительны. Получил их без клевера, на xtcoin.mdewo.com, ошибки о недействительном токене больше не было, но вылезает ошибка BrokenEvent
![image](https://user-images.githubusercontent.com/16509984/55863104-8bbff500-5b82-11e9-8539-7ee7845c06f0.png)
ЧЯДНТ?

**Comment by maksam07** [comment]
У самого недавно была подобная ошибка. Просто дальше стал ждать и со временем запустился. Ты сколько ждал запуска?

**Comment by pandaDS3** [comment]
где то пол часа
