### ISSUE TITLE
tspam 2.0

### ISSUE THREAD

**Issue by quick-wq** [xTCry/VCoin#90]
Можно добавить команду, при которой один раз выведется топ и коины, без спама? Пример:
tspam
[**.**.2019 **:**:**]: Вывод обновления коинов в консоль включен (*^.^*)
[**.**.2019 **:**:**]:  В топе: *** ***  Coins: *** *** ***,***
tspam
[**.**.2019 **:**:**]:  Вывод обновления коинов в консоль отключен (*^.^*)
Но только одной командой.

**Comment by xTCry** [comment]
What?
А как сейчас работает?

**Comment by quick-wq** [comment]
command 
[..2019 ::]: В топе: *** *** Coins: *** *** ,***
И все
Один единственный раз одной командой

**Comment by themagic314** [comment]
Добавить в "/lib/MainCore.js" если версия 1.4.6 и выше или в "/index.js" если версия меньше 1.4.6. 
Вставлять среди других case's. Пример на скриншоте. 
По команде "info" будет работать.

``` 
case 'info':
      let score = await vConinWS.getUserScores(USER_ID);
      let place = await vConinWS.getMyPlace();
      con("В топе: " + formateScore(place) + "\tCoins: "+ formateScore(score[USER_ID], true), "yellow");
      break;
```

p.s. Если что, я не умею в js. Совсем.

![photo_2019-04-10 15 47 39](https://user-images.githubusercontent.com/48516500/55879885-49a9aa00-5ba8-11e9-9a4c-f2c58fff0889.jpeg)

**Comment by xTCry** [comment]
Теперь понял о чем ты

**Comment by xTCry** [comment]
Сделал вывод, Но ещё не особо подробный

Хотя уже и не особо надо
