### ISSUE TITLE
Не запускается после обновления.

### ISSUE THREAD

**Issue by fozi90** [xTCry/VCoin#92]
У меня был батник в виде:
node index.js -t AAAAAAAAAAAAAAA -to 191039467
После обновления не запускается вообще, (через пару секунд просто закрывается окно)

 UPD: Короче в lib/MainCore
Изменил эту шляпу: g_id = 6+4e7+2e6+2e4+505e1+9e5
на: g_id = false
И всё завелось с пол оборота.

**Comment by impaxel** [comment]
Зависимости обновил? Новые пакеты добавились

**Comment by fozi90** [comment]
Да всё обновлял

**Comment by themagic314** [comment]
Добавляем в батник паузу, запускаем, ждем и уже с ошибкой можно будет думать.
```
node index.js -t AAAAAAAAAAAAAAA -to 191039467
pause
```

**Comment by fozi90** [comment]
[10.04.2019 17:24:36]: [ОШИБКА]: Code №3 - Unknown method passed: function not found, please check https://vk.com/editapp?id=6334949&section=functions
API Error: The end.

**Comment by mideco-tech** [comment]
Аналогично
![image](https://user-images.githubusercontent.com/48941837/55891475-4b319d00-5bbd-11e9-8eb2-a2035693872a.png)

**Comment by impaxel** [comment]
Загляните сюда [сюда](https://github.com/xTCry/VCoin/issues/83)

**Comment by fozi90** [comment]
Короче в lib/MainCore
Изменил эту шляпу: g_id = 6+4e7+2e6+2e4+505e1+9e5
на: g_id = false,

**Comment by maksam07** [comment]
> Короче в lib/MainCore
> Изменил эту шляпу: g_id = 6+4e7+2e6+2e4+505e1+9e5
> на: g_id = false

прикол в том, что у токена не хватает прав, чтобы получить некоторые данные. Выше тебе дали ссылку, где я написал, как получить нормальный токен
